### ISSUE TITLE
`POST /exchanges/:id/order` figure out what to do with callback result if anything

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex-js#10]
[relevant file](https://github.com/TBD54566975/tbdex-rest-api/blob/main/src/request-handlers/submit-order.ts)

**Comment by mistermoe** [comment]
done in #91

**Comment by jiyoontbd** [comment]
Reopening - this issue is still present. Context [here](https://github.com/TBD54566975/tbdex-js/pull/170#discussion_r1493010872)
